app.database.seed.enabled=false

spring.application.name=devsu-account
server.port=0

# ===== Datasource (H2) =====
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.h2.console.enabled=false

# ===== Lock (referencia; lock real en memoria en este perfil) =====
redis.host=localhost
redis.port=6379
lock.ttl-millis=60000

# ===== Kafka =====
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9094}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=account-consumer-test
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.ds.devsuaccount.infraestructure.queue.dto.EventMessage

spring.kafka.listener.auto-startup=false

# ===== MongoDB (test) =====
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/test_account?authSource=admin}
spring.mongodb.database=${SPRING_MONGODB_DATABASE:test_account}

# ===== Cache (Caffeine) =====
spring.cache.type=caffeine
spring.cache.maximumSize=100
spring.cache.expireAfterWrite=10

# ===== Logging =====
logging.level.root=WARN
logging.level.com.ds.devsuaccount=INFO
